### ISSUE TITLE
How do I get the picture of the dynamic obstacle situation?

### ISSUE THREAD

**Issue by hjw08** [teerthaaparakh/CILQR#1]
Sorry, I am rather unfamiliar with python.Could you please tell me how to modify the code to get the result of cilqr running under dynamic obstacles?

**Comment by teerthaaparakh** [comment]
To run cilqr for dynamic obstacles, 
1) In cilqr->params.py file, change line number 23, "obs_num_dyna" which is the number of dynamic obstacles. I have not tested the algorithm for 1 dynamic and 1 static obstacle. So you might have to change the line number 22 also, that is make "obs_num_stat" to 0.
2) After this, in cilqr -> initialize.py, change line number 7 if you want to change the position of static obstacle (currently it is for 3 obstacles). If you want to change initial starting position of dynamic obstacle and their speeds, change line 15 and 16 accordingly (currently it is for 3 obstacles). Also the function "obs_loc_and_num_stat" will return the trajectory of all the obstacles only when "obs_num_stat" is some number otherwise it will return none, similarly for the function "obs_loc_and_num_dyna".
